# Generated by Django 3.0 on 2020-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('VN', 'Vietnam'), ('JP', 'Japan')], default='JP', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1),
        ),
    ]
