# Generated by Django 3.0 on 2020-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0005_auto_20200208_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spoken_languages',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
