# Generated by Django 3.0 on 2020-02-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0007_auto_20200211_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DoB',
            field=models.DateField(verbose_name='Date of birth (mm/dd/yyyy format)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(blank=True, default='https://i.imgur.com/ndkX0PN.png', max_length=500, verbose_name='URL to your Profile Picture'),
        ),
    ]
