# Generated by Django 3.0 on 2020-02-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userController', '0002_auto_20200204_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pal_list', models.ManyToManyField(to='userController.Profile')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userController.Profile')),
            ],
        ),
    ]
