# Generated by Django 3.0 on 2020-02-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0004_auto_20200207_0250'),
        ('matching', '0002_matchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pal_list', to='userController.Profile'),
        ),
    ]
